version: '3'

services:

  nginx:
    image: nginx:1.19
    environment:
      VIRTUAL_HOST: influxdb.ginnungagap.docker,chronograf.ginnungagap.docker
    volumes:
    - ./Docker/Configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./.htpasswd:/etc/nginx/.htpasswd:ro
    links:
    - influxdb
    - chronograf
    env_file:
    - .env
    labels:
    - "traefik.backend=monitor-discworld"
    - "traefik.frontend.rule=Host:chronograf.monitor.discworld.dk,influxdb.monitor.discworld.dk"
    restart: unless-stopped

  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.8
    volumes:
    - ./Docker/Configuration/etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - ./Docker/Data/influxdb:/var/lib/influxdb
    env_file:
    - .env
    labels:
    - "traefik.enable=false
    restart: unless-stopped"

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
#      KAPACITOR_URL: http://kapacitor:9092
    env_file:
    - .env
    links:
    - influxdb
#    - kapacitor
    labels:
    - "traefik.enable=false"
    restart: unless-stopped


#  # Define a Telegraf service
#  telegraf:
#    image: telegraf:1.5.3
#    volumes:
#    - ./Docker/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    links:
#    - influxdb
#    ports:
#    - "8092:8092/udp"
#    - "8094:8094"
#    - "8125:8125/udp"

#  # Define a Kapacitor service
#  kapacitor:
#    image: kapacitor:1.4.1
#    environment:
#      KAPACITOR_HOSTNAME: kapacitor
#      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
#    links:
#    - influxdb
#    ports:
#    - "9092:9092"
